adding my lab
r1zhok/second_repository_2022_2 pull request #1
Opened 2022-11-30 14:23 UTC by r1zhok

2022-12-13 09:35 UTC, Vadum4567890 requested changes
change code

2022-12-13 09:35 UTC, Vadum4567890 commented on Clossing.h
> +        cout << "name = " << this->name << endl;
need to create printClothing() method for code: 
        cout << "name = " << this->name << endl;
        cout << "description = " << this->description << endl;
        cout << "location = " << this->location << endl;
        cout << "color = " << this->color << endl;
        cout << "size = " << this->size << endl;

2022-12-13 09:35 UTC, Vadum4567890 commented on lab5.cpp
> +    Clothing A("Gucci", "very nice textile", "Paris", "black", 50, Shirt),
give a normal name to Clothing objects

2022-12-13 09:35 UTC, Vadum4567890 commented on lab5.cpp
> +
Give a normal name to Wardrobe object and methods in class must have same case-style

2022-12-13 09:35 UTC, Vadum4567890 commented on Wardrobe.h
> +        int n = 0;
What is variable n? Set a correct name

2022-12-13 09:35 UTC, Vadum4567890 commented on Wardrobe.h
> +    vector<Clothing> Clo;
Change Clo object to Clothing

2022-12-13 09:45 UTC, Vadum4567890 requested changes

2022-12-13 09:45 UTC, Vadum4567890 commented on Clossing.h
> +    string name;
set Clothing data to private: 
    string name;
    string description;
    string location;
    string color;
    int size;
    Type type;

2023-02-25 21:40 UTC, zveres-ss requested changes

2023-02-25 21:40 UTC, zveres-ss commented on lab5.cpp
> +    Clothing Shirt("Gucci", "very nice textile", "Paris", "black", 50, Shirt),
variable names should start from lowercase letter

2023-05-14 13:17 UTC, merged